import AppKit

enum PasteboardTypes {
    static let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .string,
        .rtf,
        .html,
        .png,
        .tiff,
        .fileURL,
        .pdf,
    ]

    static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private static let ignoredPrefixes = [
        "dyn.",
        "com.microsoft.ole.source",
    ]

    static func shouldCapture(_ type: NSPasteboard.PasteboardType) -> Bool {
        let raw = type.rawValue
        for prefix in ignoredPrefixes {
            if raw.hasPrefix(prefix) { return false }
        }
        return supportedTypes.contains(type)
    }

    static func isConcealed(_ item: NSPasteboardItem) -> Bool {
        let types = Set(item.types)
        return !types.isDisjoint(with: concealedTypes)
    }
}
